### ISSUE TITLE
agregar aclaracion de que la contraseña no se ve

### ISSUE THREAD

**Issue by princesamee** [introprog-dc/tallerDeGit#14]
Cuando se escribe la contraseña parece que no se escribió o pego nada en la terminal, esto es por seguridad. Pero en verdad todo lo que se esciba esta siendo usado como parte de la contraseña.

https://github.com/introprog-dc/tallerDeGit/blob/7b46718e6952f8b79d9fe2ff7b8c3dda692bb5c0/taller_git.md?plain=1#L514

**Comment by introprog-dc** [comment]
Solucionado en d0849c2
